export default [
  {
    _id: "QZ101",
    name: "Basics of Rocket Propulsion",
    course: "RS101",
    type: "Graded Quiz", // Default type
    points: 50,
    assignmentGroup: "Quizzes", // Default group
    shuffleAnswers: "No", // Default shuffle answer
    timeLimit: "30min", // Default time limit
    multipleAttempts: "No", // Default multiple attempts
    showCorrectAnswers: "No", // Default option to show correct answers
    accessCode: "", // Default access code is blank
    oneQuestionAtATime: "No", // Default setting
    webcamRequired: "No", // Default webcam requirement
    lockQuestionsAfterAnswering: "No", // Default lock setting
    dueDate: "2023-04-15", // Existing due date
    status: "Not available until", // Existing status
    availableDate: "2023-02-01", // Existing available date
    untilDate: "2023-05-01", // Existing end date
    numberOfQuestions: 10, // Existing number of questions
    published: false, // Existing publish status
  },
  {
    _id: "QZ102",
    name: "Introduction to Aerodynamics",
    course: "RS102",
    type: "Graded Quiz",
    points: 40,
    assignmentGroup: "Quizzes",
    shuffleAnswers: "No",
    timeLimit: "30min",
    multipleAttempts: "No",
    showCorrectAnswers: "No",
    accessCode: "",
    oneQuestionAtATime: "No",
    webcamRequired: "No",
    lockQuestionsAfterAnswering: "No",
    dueDate: "2023-04-20",
    status: "Available",
    availableDate: "2023-01-15",
    untilDate: "2023-05-01",
    numberOfQuestions: 8,
    published: true,
  },
  {
    _id: "QZ103",
    name: "Spacecraft Systems Quiz",
    course: "RS103",
    type: "Graded Quiz",
    points: 60,
    assignmentGroup: "Quizzes",
    shuffleAnswers: "No",
    timeLimit: "30min",
    multipleAttempts: "No",
    showCorrectAnswers: "No",
    accessCode: "",
    oneQuestionAtATime: "No",
    webcamRequired: "No",
    lockQuestionsAfterAnswering: "No",
    dueDate: "2023-02-28",
    status: "Closed",
    availableDate: "2023-01-20",
    untilDate: "2023-03-01",
    numberOfQuestions: 12,
    published: true,
  },
  {
    _id: "QZ104",
    name: "Organic Chemistry Basics",
    course: "RS104",
    type: "Graded Quiz",
    points: 70,
    assignmentGroup: "Quizzes",
    shuffleAnswers: "No",
    timeLimit: "30min",
    multipleAttempts: "No",
    showCorrectAnswers: "No",
    accessCode: "",
    oneQuestionAtATime: "No",
    webcamRequired: "No",
    lockQuestionsAfterAnswering: "No",
    dueDate: "2023-05-30",
    status: "Available",
    availableDate: "2023-01-25",
    untilDate: "2023-06-01",
    numberOfQuestions: 15,
    published: false,
  },
  {
    _id: "QZ105",
    name: "Inorganic Chemistry Applications",
    course: "RS105",
    type: "Graded Quiz",
    points: 50,
    assignmentGroup: "Quizzes",
    shuffleAnswers: "No",
    timeLimit: "30min",
    multipleAttempts: "No",
    showCorrectAnswers: "No",
    accessCode: "",
    oneQuestionAtATime: "No",
    webcamRequired: "No",
    lockQuestionsAfterAnswering: "No",
    dueDate: "2023-06-10",
    status: "Not available until",
    availableDate: "2023-03-10",
    untilDate: "2023-06-15",
    numberOfQuestions: 10,
    published: false,
  },
  {
    _id: "QZ106",
    name: "Elvish Linguistics Quiz",
    course: "RS107",
    type: "Graded Quiz",
    points: 100,
    assignmentGroup: "Quizzes",
    shuffleAnswers: "No",
    timeLimit: "30min",
    multipleAttempts: "No",
    showCorrectAnswers: "No",
    accessCode: "",
    oneQuestionAtATime: "No",
    webcamRequired: "No",
    lockQuestionsAfterAnswering: "No",
    dueDate: "2023-05-10",
    status: "Available",
    availableDate: "2023-01-15",
    untilDate: "2023-05-15",
    numberOfQuestions: 20,
    published: true,
  },
];
